name: release

env:
  TEST_COVERAGE_THRESHOLD: 100
  PR_APPROVALS_FILENAME: "pr_approvals"
  RELEASE_REPORT_FILENAME: "release_report"
  RELEASE_DOCUMENTATION: "release_docs.tar.gz"

on:
  push:
    branches:
      - "main"

jobs:
  quality-assurance:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: 'install uv'
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
    - name: install requirements
      run: ./helper.sh reqs
    - name: create report header
      shell: bash
      run: ./helper.sh report_header "${{ env.RELEASE_REPORT_FILENAME }}.md" "${{ github.repository }}" "${{ github.ref }}" "${{ github.sha }}"
    - name: code quality (linter) check
      shell: bash
      run: ./helper.sh function_report_wrapper "${{ env.RELEASE_REPORT_FILENAME }}.md" "code quality (linter) check" ./helper.sh linter_check
    - name: code quality (sca - safety) check
      shell: bash
      run: ./helper.sh function_report_wrapper "${{ env.RELEASE_REPORT_FILENAME }}.md" "code quality (sca - safety) check" ./helper.sh sca_check
      env:
        SAFETY_KEY: ${{ secrets.SAFETY_KEY }} 
    - name: "code quality (sast - bandit) check"
      shell: bash
      run: ./helper.sh function_report_wrapper "${{ env.RELEASE_REPORT_FILENAME }}.md" "code quality (sast - bandit) check" ./helper.sh sast_check
    - name: unit tests
      shell: bash
      run: ./helper.sh function_report_wrapper "${{ env.RELEASE_REPORT_FILENAME }}.md" "unit tests" ./helper.sh test
    - name: unit test coverage
      shell: bash
      run: ./helper.sh function_report_wrapper "${{ env.RELEASE_REPORT_FILENAME }}.md" "unit test coverage" ./helper.sh test_coverage_check ${{ env.TEST_COVERAGE_THRESHOLD }}
    - name: create release report
      run: ./helper.sh generate_pdf_from_md "${{ env.RELEASE_REPORT_FILENAME }}.md" "${{ env.RELEASE_REPORT_FILENAME }}.pdf"
    - name: generate pr approvals report
      shell: bash
      run: |
        ./helper.sh generate_pr_approvals "${{ env.PR_APPROVALS_FILENAME }}.md" && \
        ./helper.sh generate_pdf_from_md "${{ env.PR_APPROVALS_FILENAME }}.md" "${{ env.PR_APPROVALS_FILENAME }}.pdf"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    - name: collect git folder
      run: ./helper.sh collect_dot_git
    - name: create release documentation
      run: ./helper.sh create_release_documentation "${{ env.PR_APPROVALS_FILENAME }}.pdf" "${{ env.RELEASE_REPORT_FILENAME }}.pdf"
    - name: Upload release documentation
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.RELEASE_DOCUMENTATION }} 
        path: ${{ env.RELEASE_DOCUMENTATION }} 

  build-publish:
    needs: quality-assurance
    runs-on: ubuntu-24.04
    environment: prd
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: 'install uv'
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
    - name: install requirements
      run: ./helper.sh reqs
    - name: fetch release documentation
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.RELEASE_DOCUMENTATION }} 
    - name: build
      run: ./helper.sh build
    - name: publish
      run: ./helper.sh publish
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}        